<?php

return [
  'roles' => [
    'Administrator',
    'Patient',
  ],

  'types' => [
    (object) [
      'value' => 'General',
      'text' => 'General',
    ],
    (object) [
      'value' => 'JKN',
      'text' => 'JKN (National Health Insurance)',
    ],
  ],

  'status' => [
    (object) [
      'value' => 'Married',
      'text' => 'I\'m married',
    ],
    (object) [
      'value' => 'Single',
      'text' => 'I\'m not married',
    ],
  ],

  'specialists' => [
    'Sp. Kandungan & Kebidanan',
    'Sp. Kulit & Kelamin',
    'Sp. THT',
    'Sp. Jiwa',
    'Sp. Penyakit Dalam',
    'Sp. Anak',
    'Sp. Mata',
    'Dokter Gigi',
    'Dokter Umum',
    'Psikolog Klinis',
    'Sp. Saraf',
    'Sp. Paru',
    'Sp. Urologi',
    'Sp. Orthopaedi & Traumatologi',
    'Sp. Jantung & Pembuluh Darah',
    'Sp. PD Gastroenterologi - Hepatologi',
    'Sp. Bedah Umum',
    'Sp. Gizi Klinik',
    'Sp. PD Endokrin - Metabolik - Diabetes',
    'Sp. Andrologi',
    'Sp. Konservasi Gigi',
    'Dokter Bedah',
    'Sp. PD Ginjal - Hipertensi',
    'Sp. Gigi Anak',
    'Sp. Bedah Onkologi',
    'Sp. PD Reumatologi',
    'Sp. PD Hematologi & Onkologi Medik',
    'Sp. Bedah Mulut & Maksilofasial',
    'Sp. Bedah Saraf',
    'Sp. Rehabilitasi Medik & Kedokteran Fisik',
    'Sp. Ortodonsia',
    'Sp. Periodonsia',
    'Sp. Kedokteran Olahraga',
    'Psikolog Klinis Anak & Remaja',
    'Sp. PD Kardiovaskular',
    'Sp. Bedah Digestif',
    'Akupuntur',
    'Sp. Bedah Plastik',
    'Sp. Bedah Toraks Kardiovaskular',
    'Sp. Bedah Anak',
    'Fisioterapis',
    'Sp. Prostodonsia',
    'Sp. Bedah Vaskuler & Endovaskuler',
    'Sp. Penyakit Mulut',
    'Sp. PD Alergi - Imunologi',
    'Sp. PD Tropik - Infeksi',
    'Konselor Laktasi',
    'Sp. Bedah Spine',
    'Psikolog Klinis Dewasa',
    'Sp. Mikrobiologi Klinik',
    'Sp. Bedah Panggul & Lutut',
    'Dokter Kecantikan',
    'Sp. Radiologi',
    'Sp. Anestesiologi',
    'Sp. Okupasi',
    'Sp. Onkologi Radiasi',
    'Sp. Patologi Anatomi',
    'Sp. Patologi Klinik',
    'Bidan',
    'Dokter Forensik',
    'General Practitioner (Elderly Care)',
    'Hipnoterapis',
    'Sp. Anak (Onkologi)',
    'Sp. Farmakologi Klinik',
    'Sp. Intervensi dan Kegawatdaruratan Napas',
    'Sp. Kedokteran Nuklir',
    'Sp. Nutrisi pada Kelainan Metabolisme',
    'Dokter Gigi Spesialis Radiologi - Subspesialis Radiodiagnosis Imaging',
    'Ahli Gizi',
    'Dokter Emergensi Medik',
    'Dokter Gigi Kosmetik',
    'Dokter Gigi Sp. Radiologi',
    'Dokter Hewan',
    'Ilmu Biomedik',
    'Konselor',
    'Konsultasi Medis',
    'Psikolog Non Klinis',
    'Sp. Anak (Gastroenterologi-Hepatologi)',
    'Sp. Anak (Nefrologi)',
    'Sp. Anak (Neonatologi)',
    'Sp. Anak (Neurologi)',
    'Sp. Anak (Nutrisi & Penyakit Metabolik)',
    'Sp. Anak (Penyakit Tropik-Infeksi)',
    'Sp. Anak (Tumbuh Kembang)',
    'Sp. Fetomaternal',
    'Sp. Gizi Klink (Konsultan Endokrin Metabolik)',
    'Sp. Jantung (Kardiologi Intervensi)',
    'Sp. Kedokteran Kelautan',
    'Sp. Kedokteran Keluarga Layanan Primer',
    'Sp. Kedokteran Penerbangan',
    'Sp. PD Geriatri',
    'Sp. PD Psikosomatik',
    'Sp. THT (Bronko-Esofagologi)',
    'Spesialis Bedah Toraks Kardiak & Vaskular - Konsultan Vaskular EndoVaskular',
    'Spesialis Kedokteran Olahraga (Ahli Latihan dan Kompetisi)',
    'Spesialis Orthopedi Olahraga dan Artroskopi',
    'Spesialis Penyakit Dalam (Pulmonologi)',
    'Spesialis Saraf Konsultan Nyeri',
    'Lainnya',
  ],

  'days' => [
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Sunday',
  ],
];
